export default {
  updateInterval: 2000,
  account: null,
  balance: null,
  network: null,
  netId: null,
  unlocked: null,
  rpcURL: null,
  blockNumber: null,
  gasPrice: null,
  fallbackHost: 'http://mainnet.infura.io',
  connected: null,
  isInjected: null,
  provider: null,
  metamaskDisabled: false,
};
